import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';
import { SchemaService } from '../../services/schema.service';
import { GenericCrudService } from '../../services/generic-crud.service';
import { EntitySchema, FieldDefinition, SelectOption } from '../../models/entity-schema.model';
import { AudioRecorderService } from '../../services/audio-recorder.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-clinical-encounter-form',
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './clinical-encounter-form.component.html',
  styleUrl: './clinical-encounter-form.component.scss'
})
export class ClinicalEncounterFormComponent implements OnInit {
  private route    = inject(ActivatedRoute);
  private router   = inject(Router);
  private fb       = inject(FormBuilder);
  private schemaSvc = inject(SchemaService);
  private crudSvc  = inject(GenericCrudService);
  private auth     = inject(AuthService);
  readonly recorder = inject(AudioRecorderService);
  readonly AudioRecorderService = AudioRecorderService;

  schema    = signal<EntitySchema | null>(null);
  entityKey = signal('');
  recordId  = signal<number | null>(null);
  saving    = signal(false);
  saved     = signal(false);
  saveError = signal<string | null>(null);

  savingVitals      = signal(false);
  savedVitals       = signal(false);
  vitalsError       = signal<string | null>(null);
  savingDiagnosis   = signal(false);
  savedDiagnosis    = signal(false);
  diagnosisError    = signal<string | null>(null);
  savingBackground  = signal(false);
  savedBackground   = signal(false);
  backgroundError   = signal<string | null>(null);

  form!: FormGroup;

  /**
   * Campos editables del encuentro: vitales, diagnóstico y nota SOAP.
   * Los datos estables del paciente se muestran como resumen de solo lectura.
   * Campos de anamnesis/antecedentes (history, surgical, medications, alerts)
   * se editan en la ficha principal, no aquí.
   */
  private static readonly ENCOUNTER_SECTIONS    = new Set(['vitals', 'diagnosis', 'soap']);
  private static readonly BACKGROUND_SECTIONS  = new Set(['history', 'surgical', 'medications', 'alerts']);

  editableFields = computed(() => {
    const fields = this.schema()?.fields ?? [];
    const allSections = new Set([
      ...ClinicalEncounterFormComponent.ENCOUNTER_SECTIONS,
      ...ClinicalEncounterFormComponent.BACKGROUND_SECTIONS,
    ]);
    const excluded = (f: FieldDefinition) =>
      f.type === 'object-list' || f.type === 'dental-chart' || f.type === 'periodontal-chart' ||
      f.isAutoGenerated || f.type === 'entity-select' || !!f.displayOnly ||
      !!f.isStable || !!f.hideInEncounterMode;
    return fields.filter(f => !!f.section && allSections.has(f.section) && !excluded(f));
  });

  backgroundFields = computed(() =>
    this.editableFields().filter(f =>
      ClinicalEncounterFormComponent.BACKGROUND_SECTIONS.has(f.section ?? '')
    )
  );

  private static readonly SECTION_HEADINGS: Record<string, string> = {
    vitals:       'Signos Vitales',
    diagnosis:    'Diagnóstico',
    soap:         'Nota SOAP',
    history:      'Antecedentes',
    surgical:     'Intervenciones Quirúrgicas',
    medications:  'Medicación',
    alerts:       'Alertas Clínicas',
  };

  /** Fields grouped by section, preserving schema order. */
  readonly editableFieldsBySection = computed(() => {
    const groups: { section: string; label: string; fields: FieldDefinition[] }[] = [];
    for (const f of this.editableFields()) {
      const s = f.section ?? '';
      let g = groups.find(g => g.section === s);
      if (!g) {
        g = { section: s, label: ClinicalEncounterFormComponent.SECTION_HEADINGS[s] ?? s, fields: [] };
        groups.push(g);
      }
      g.fields.push(f);
    }
    return groups;
  });

  /** Campos estables del paciente, para mostrar como resumen de solo lectura */
  stableFields = computed(() =>
    this.schema()?.fields.filter(f => f.isStable && f.type !== 'entity-select' && !f.displayOnly) ?? []
  );

  ngOnInit() {
    const key    = this.route.snapshot.paramMap.get('entityKey') ?? '';
    const idParam = this.route.snapshot.paramMap.get('id');

    this.entityKey.set(key);
    this.schema.set(this.schemaSvc.getSchema(key));
    this.crudSvc.initStore(key);

    // Pre-load stores for every select field backed by a lookupEntity
    this.schema()?.fields
      .filter(f => f.type === 'select' && f.lookupEntity)
      .forEach(f => this.crudSvc.initStore(f.lookupEntity!));

    if (idParam) this.recordId.set(+idParam);

    this.buildForm();

    if (this.recordId() !== null) {
      const record = this.crudSvc.getById(key, this.recordId()!);
      if (record) {
        const patch: Record<string, any> = {};
        this.schema()!.fields
          .filter(f => f.isStable)
          .forEach(f => {
            patch[f.name] = f.type === 'tags' && Array.isArray(record[f.name])
              ? record[f.name].join(', ')
              : (record[f.name] ?? '');
          });
        this.form.patchValue(patch);
        this.form.patchValue({ encounterDate: new Date().toISOString().slice(0, 10) });
      }
    }
  }

  private buildForm() {
    const group: Record<string, any> = {};
    const fields = this.schema()?.fields.filter(f =>
      f.type !== 'object-list' && f.type !== 'dental-chart' && f.type !== 'periodontal-chart' &&
      !f.isAutoGenerated && !f.displayOnly
    ) ?? [];

    fields.forEach(f => {
      const validators = [];
      if (f.requiredInEncounter) validators.push(Validators.required);
      if (f.type === 'email')    validators.push(Validators.email);
      if (f.pattern)             validators.push(Validators.pattern(f.pattern));
      if (f.minLength)           validators.push(Validators.minLength(f.minLength));
      if (f.maxLength)           validators.push(Validators.maxLength(f.maxLength));
      if (f.min !== undefined && f.type === 'number') validators.push(Validators.min(f.min));
      if (f.max !== undefined && f.type === 'number') validators.push(Validators.max(f.max));

      let defaultVal: any = '';
      if (f.type === 'number')  defaultVal = f.min ?? 0;
      if (f.type === 'range')   defaultVal = f.min ?? 0;
      if (f.type === 'boolean') defaultVal = false;
      if (f.options?.length)    defaultVal = f.options[0].value;

      group[f.name] = [{ value: defaultVal, disabled: !!f.isStable }, validators];
    });

    group['encounterDate'] = [new Date().toISOString().slice(0, 10), [Validators.required]];
    this.form = this.fb.group(group);

    // BMI is auto-calculated from weight and height — disable editing
    if (this.form.get('bmi')) {
      this.form.get('bmi')!.disable({ emitEvent: false });
      this.form.get('weight')?.valueChanges.subscribe(() => this.recalcBmi());
      this.form.get('height')?.valueChanges.subscribe(() => this.recalcBmi());
    }
  }

  private recalcBmi(): void {
    const weight = parseFloat(this.form.get('weight')?.value);
    const height = parseFloat(this.form.get('height')?.value);
    if (weight > 0 && height > 0) {
      const bmi = Math.round((weight / Math.pow(height / 100, 2)) * 10) / 10;
      this.form.get('bmi')?.setValue(bmi, { emitEvent: false });
    }
  }

  ctrl(name: string): AbstractControl { return this.form.get(name)!; }

  isInvalid(name: string): boolean {
    const c = this.form.get(name);
    return !!(c?.invalid && c.touched);
  }

  getError(name: string, field: FieldDefinition): string {
    const errors = this.form.get(name)?.errors;
    if (!errors) return '';
    if (errors['required'])   return `${field.label} es obligatorio.`;
    if (errors['email'])      return 'El email no es válido.';
    if (errors['pattern'])    return field.patternMessage ?? 'El formato no es válido.';
    if (errors['minlength'])  return `Mínimo ${field.minLength} caracteres.`;
    if (errors['maxlength'])  return `Máximo ${field.maxLength} caracteres.`;
    if (errors['min'])        return `El valor mínimo es ${field.min}.`;
    if (errors['max'])        return `El valor máximo es ${field.max}.`;
    return '';
  }

  getInputType(field: FieldDefinition): string {
    if (field.type === 'tags')     return 'text';
    if (field.type === 'datetime') return 'datetime-local';
    return field.type as string;
  }

  getFieldOptions(field: FieldDefinition): SelectOption[] {
    if (!field.lookupEntity) return field.options ?? [];
    const vf = field.lookupValueField ?? 'id';
    const lf = field.lookupLabelField ?? 'label';
    return this.crudSvc.getAll(field.lookupEntity)().map(item => ({
      value: String(item[vf] ?? item['id']),
      label: String(item[lf] ?? item['label'] ?? item[vf] ?? item['id']),
    }));
  }

  saveVitals(): void {
    this.savingVitals.set(true);
    this.savedVitals.set(false);
    this.vitalsError.set(null);
    const raw  = this.form.getRawValue();
    const data: Record<string, any> = {};
    this.editableFields()
      .filter(f => f.section === 'vitals')
      .forEach(f => {
        const v = raw[f.name];
        if (v !== undefined && v !== '' && v !== null) {
          data[f.name] = (f.type === 'number' || f.type === 'range') ? Number(v) : v;
        }
      });
    this.crudSvc.update(this.entityKey(), this.recordId()!, data).subscribe({
      next: () => { this.savingVitals.set(false); this.savedVitals.set(true); },
      error: err => { this.savingVitals.set(false); this.vitalsError.set(err?.error?.message ?? 'Error al guardar los signos vitales'); }
    });
  }

  saveDiagnosis(): void {
    this.savingDiagnosis.set(true);
    this.savedDiagnosis.set(false);
    this.diagnosisError.set(null);
    const raw  = this.form.getRawValue();
    const data: Record<string, any> = {};
    this.editableFields()
      .filter(f => f.section === 'diagnosis')
      .forEach(f => {
        const v = raw[f.name];
        if (v !== undefined && v !== '' && v !== null) {
          data[f.name] = v;
        }
      });
    this.crudSvc.update(this.entityKey(), this.recordId()!, data).subscribe({
      next: () => { this.savingDiagnosis.set(false); this.savedDiagnosis.set(true); },
      error: err => { this.savingDiagnosis.set(false); this.diagnosisError.set(err?.error?.message ?? 'Error al guardar el diagnóstico'); }
    });
  }

  saveBackground(): void {
    this.savingBackground.set(true);
    this.savedBackground.set(false);
    this.backgroundError.set(null);
    const raw  = this.form.getRawValue();
    const data: Record<string, any> = {};
    this.backgroundFields().forEach(f => {
      const v = raw[f.name];
      if (v !== undefined && v !== null && v !== '') {
        const parsed = f.type === 'tags'
          ? String(v).split(',').map((s: string) => s.trim()).filter(Boolean)
          : v;
        if (f.type === 'tags' ? (parsed as string[]).length > 0 : true) {
          data[f.name] = parsed;
        }
      }
    });
    if (Object.keys(data).length === 0) {
      this.savingBackground.set(false);
      this.backgroundError.set('No hay antecedentes que guardar.');
      return;
    }
    this.crudSvc.update(this.entityKey(), this.recordId()!, data).subscribe({
      next: () => { this.savingBackground.set(false); this.savedBackground.set(true); },
      error: err => { this.savingBackground.set(false); this.backgroundError.set(err?.error?.message ?? 'Error al guardar los antecedentes'); }
    });
  }

  submit() {
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    this.saving.set(true);
    this.saveError.set(null);
    const raw = this.form.getRawValue();

    // Persist background fields to the clinical record top-level columns only when
    // the doctor actually filled them in (avoid overwriting existing data with blanks).
    const backgroundData: Record<string, any> = {};
    this.backgroundFields().forEach(f => {
      const v = raw[f.name];
      if (v !== undefined && v !== null && v !== '') {
        const parsed = f.type === 'tags'
          ? String(v).split(',').map((s: string) => s.trim()).filter(Boolean)
          : v;
        if (f.type === 'tags' ? (parsed as string[]).length > 0 : true) {
          backgroundData[f.name] = parsed;
        }
      }
    });
    if (Object.keys(backgroundData).length > 0) {
      this.crudSvc.update(this.entityKey(), this.recordId()!, backgroundData).subscribe();
    }

    const encounter: Record<string, any> = { encounterDate: raw['encounterDate'], status: 'active', soapSource: 'manual' };
    this.schema()!.fields
      .filter(f =>
        !f.isStable &&
        f.type !== 'object-list' && f.type !== 'dental-chart' && f.type !== 'periodontal-chart'
      )
      .forEach(f => {
        const v = raw[f.name];
        if (v !== undefined && v !== '' && v !== null) {
          encounter[f.name] = (f.type === 'number' || f.type === 'range') ? Number(v) : v;
        }
      });

    this.crudSvc.appendEncounter(this.entityKey(), this.recordId()!, encounter).subscribe({
      next: async updated => {
        const decrypted = await this.crudSvc.decryptAndUpdate(this.entityKey(), this.recordId()!, updated);
        this.saving.set(false);
        this.saved.set(true);
        setTimeout(() => this.router.navigate(['/app/clinical', this.entityKey(), this.recordId()]), 800);
      },
      error: err => {
        this.saving.set(false);
        this.saveError.set(err?.error?.message ?? 'Error al registrar la atención. Intenta de nuevo.');
      }
    });
  }

  cancel() {
    this.router.navigate(['/app/clinical', this.entityKey(), this.recordId()]);
  }

  toggleRecording(): void {
    if (this.recorder.isRecording) {
      this.recorder.stop();
    } else {
      const user = this.auth.user();
      this.recorder.start({
        patientName: this.form.get('fullName')?.value || 'paciente',
        patientRut:  this.form.get('rut')?.value      || '',
        doctorId:    user?.id   ?? 0,
        doctorName:  user?.name ?? 'profesional',
        entityKey:   this.entityKey(),
        recordId:    this.recordId()!
      });
    }
  }
}
