import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';
import { SchemaService } from '../../services/schema.service';
import { GenericCrudService } from '../../services/generic-crud.service';
import { EntitySchema, FieldDefinition, SelectOption } from '../../models/entity-schema.model';
import { AudioRecorderService } from '../../services/audio-recorder.service';

@Component({
  selector: 'app-clinical-encounter-form',
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './clinical-encounter-form.component.html',
  styleUrl: './clinical-encounter-form.component.scss'
})
export class ClinicalEncounterFormComponent implements OnInit {
  private route    = inject(ActivatedRoute);
  private router   = inject(Router);
  private fb       = inject(FormBuilder);
  private schemaSvc = inject(SchemaService);
  private crudSvc  = inject(GenericCrudService);
  readonly recorder = inject(AudioRecorderService);
  readonly AudioRecorderService = AudioRecorderService;

  schema    = signal<EntitySchema | null>(null);
  entityKey = signal('');
  recordId  = signal<number | null>(null);
  saving    = signal(false);
  saved     = signal(false);

  form!: FormGroup;

  /**
   * Campos editables del encuentro: SÓLO los campos de la nota SOAP
   * (section === 'soap'). Los datos permanentes obligatorios del paciente
   * se muestran aparte como resumen de solo lectura (stableFields) y la fecha
   * de la atención se renderiza por separado. El resto de campos clínicos
   * opcionales quedan ocultos en el formulario de atención.
   */
  editableFields = computed(() => {
    const fields = this.schema()?.fields ?? [];
    const excluded = (f: FieldDefinition) =>
      f.type === 'object-list' || f.type === 'dental-chart' || f.type === 'periodontal-chart' ||
      f.isAutoGenerated || f.type === 'entity-select' || !!f.displayOnly ||
      !!f.isStable || !!f.hideInEncounterMode;
    return fields.filter(f => f.section === 'soap' && !excluded(f));
  });

  /** Campos estables del paciente, para mostrar como resumen de solo lectura */
  stableFields = computed(() =>
    this.schema()?.fields.filter(f => f.isStable && f.type !== 'entity-select') ?? []
  );

  ngOnInit() {
    const key    = this.route.snapshot.paramMap.get('entityKey') ?? '';
    const idParam = this.route.snapshot.paramMap.get('id');

    this.entityKey.set(key);
    this.schema.set(this.schemaSvc.getSchema(key));
    this.crudSvc.initStore(key);

    if (idParam) this.recordId.set(+idParam);

    this.buildForm();

    if (this.recordId() !== null) {
      const record = this.crudSvc.getById(key, this.recordId()!);
      if (record) {
        const patch: Record<string, any> = {};
        this.schema()!.fields.filter(f => f.isStable).forEach(f => {
          patch[f.name] = f.type === 'tags' && Array.isArray(record[f.name])
            ? record[f.name].join(', ')
            : (record[f.name] ?? '');
        });
        this.form.patchValue(patch);
        this.form.patchValue({ encounterDate: new Date().toISOString().slice(0, 10) });
      }
    }
  }

  private buildForm() {
    const group: Record<string, any> = {};
    const fields = this.schema()?.fields.filter(f =>
      f.type !== 'object-list' && f.type !== 'dental-chart' && f.type !== 'periodontal-chart' &&
      !f.isAutoGenerated && !f.displayOnly
    ) ?? [];

    fields.forEach(f => {
      const validators = [];
      if (f.requiredInEncounter) validators.push(Validators.required);
      if (f.type === 'email')    validators.push(Validators.email);
      if (f.pattern)             validators.push(Validators.pattern(f.pattern));
      if (f.minLength)           validators.push(Validators.minLength(f.minLength));
      if (f.maxLength)           validators.push(Validators.maxLength(f.maxLength));
      if (f.min !== undefined && f.type === 'number') validators.push(Validators.min(f.min));
      if (f.max !== undefined && f.type === 'number') validators.push(Validators.max(f.max));

      let defaultVal: any = '';
      if (f.type === 'number')  defaultVal = f.min ?? 0;
      if (f.type === 'range')   defaultVal = f.min ?? 0;
      if (f.type === 'boolean') defaultVal = false;
      if (f.options?.length)    defaultVal = f.options[0].value;

      group[f.name] = [{ value: defaultVal, disabled: !!f.isStable }, validators];
    });

    group['encounterDate'] = [new Date().toISOString().slice(0, 10), [Validators.required]];
    this.form = this.fb.group(group);
  }

  ctrl(name: string): AbstractControl { return this.form.get(name)!; }

  isInvalid(name: string): boolean {
    const c = this.form.get(name);
    return !!(c?.invalid && c.touched);
  }

  getError(name: string, field: FieldDefinition): string {
    const errors = this.form.get(name)?.errors;
    if (!errors) return '';
    if (errors['required'])   return `${field.label} es obligatorio.`;
    if (errors['email'])      return 'El email no es válido.';
    if (errors['pattern'])    return field.patternMessage ?? 'El formato no es válido.';
    if (errors['minlength'])  return `Mínimo ${field.minLength} caracteres.`;
    if (errors['maxlength'])  return `Máximo ${field.maxLength} caracteres.`;
    if (errors['min'])        return `El valor mínimo es ${field.min}.`;
    if (errors['max'])        return `El valor máximo es ${field.max}.`;
    return '';
  }

  getInputType(field: FieldDefinition): string {
    if (field.type === 'tags')     return 'text';
    if (field.type === 'datetime') return 'datetime-local';
    return field.type as string;
  }

  getFieldOptions(field: FieldDefinition): SelectOption[] {
    if (!field.lookupEntity) return field.options ?? [];
    return this.crudSvc.getAll(field.lookupEntity)().map(item => ({
      value: String(item['id']),
      label: String(item['label'])
    }));
  }

  submit() {
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    this.saving.set(true);
    const raw = this.form.getRawValue();

    setTimeout(() => {
      const encounter: Record<string, any> = { encounterDate: raw['encounterDate'], status: 'active' };
      this.schema()!.fields
        .filter(f =>
          !f.isStable &&
          f.type !== 'object-list' && f.type !== 'dental-chart' && f.type !== 'periodontal-chart'
        )
        .forEach(f => {
          const v = raw[f.name];
          if (v !== undefined && v !== '' && v !== null) {
            encounter[f.name] = (f.type === 'number' || f.type === 'range') ? Number(v) : v;
          }
        });

      this.crudSvc.appendEncounter(this.entityKey(), this.recordId()!, encounter);
      this.saving.set(false);
      this.saved.set(true);
      setTimeout(() => this.router.navigate(['/app/clinical', this.entityKey(), this.recordId()]), 800);
    }, 400);
  }

  cancel() {
    this.router.navigate(['/app/clinical', this.entityKey(), this.recordId()]);
  }

  toggleRecording(): void {
    if (this.recorder.isRecording) {
      this.recorder.stop();
    } else {
      this.recorder.start({
        patientName: this.form.get('fullName')?.value || 'paciente',
        entityKey:   this.entityKey(),
        recordId:    this.recordId()!
      });
    }
  }
}
