export type FieldType =
  | 'text'
  | 'email'
  | 'number'
  | 'select'
  | 'textarea'
  | 'date'
  | 'datetime'
  | 'boolean'
  | 'url'
  | 'tel'
  | 'range'
  | 'tags'
  | 'object-list'
  | 'dental-chart'
  | 'periodontal-chart'
  | 'entity-select';

/** Determines which view component renders this entity's overview */
export type ModuleType = 'crud' | 'list' | 'calendar' | 'clinical-record' | 'presupuestos' | 'admin';

export type FieldFormat = 'currency' | 'date' | 'stars' | 'percent' | 'none';
export type FilterType = 'search' | 'select';

export interface SelectOption {
  value: string;
  label: string;
}

export interface FieldDefinition {
  name: string;
  type: FieldType;
  label: string;
  required?: boolean;
  showInList?: boolean;
  showInDetail?: boolean;
  isTitle?: boolean;
  isSubtitle?: boolean;
  isBadge?: boolean;
  options?: SelectOption[];
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  pattern?: string;
  patternMessage?: string;
  minLength?: number;
  maxLength?: number;
  sortable?: boolean;
  filterable?: boolean;
  filterType?: FilterType;
  format?: FieldFormat;
  badgeColors?: Record<string, string>;
  isCalendarStart?: boolean;
  isCalendarEnd?: boolean;
  section?: string;
  isVitalSign?: boolean;
  isAlert?: boolean;
  /**
   * When true, this field does not change between patient encounters.
   * In encounter mode the generic-form renders it read-only.
   */
  isStable?: boolean;
  /**
   * When true, the clinical-detail shows a "Imprimir Receta" button
   * next to this field's section, generating a printable prescription.
   */
  isPrescription?: boolean;
  /** When true, the field belongs to the surgical interventions section */
  isSurgical?: boolean;
  /**
   * When true, the field value is auto-generated by the backend on creation.
   * The field is never shown in create/edit forms; on edit, the existing value
   * is preserved automatically.
   */
  isAutoGenerated?: boolean;
  /**
   * When true, the field becomes read-only once the record has at least one
   * encounter registered. Prevents retroactive changes to critical clinical data.
   */
  lockWhenHasEncounters?: boolean;
  /**
   * When true, this field is encrypted at rest using AES-256-GCM (Zero-Knowledge model).
   * The server only stores ciphertext; only the user's derived key can decrypt it.
   */
  encrypted?: boolean;
  /**
   * For type='select': load options dynamically from this entity key via the
   * CRUD service instead of using the hardcoded `options` array.
   * Use lookupValueField / lookupLabelField to specify which row fields to use.
   * Defaults to 'id' for value and 'label' for label.
   */
  lookupEntity?: string;
  /** Field name in the lookup entity whose value is stored in the record (default: 'id') */
  lookupValueField?: string;
  /** Field name in the lookup entity displayed to the user (default: 'label') */
  lookupLabelField?: string;
  /** For type='entity-select': which entity key to load options from */
  relatedEntity?: string;
  /** Field name in the related entity to use as display label */
  relatedLabelField?: string;
  /** Auto-fill other form fields when this entity-select changes */
  linkedFields?: Array<{ from: string; to: string }>;
  /**
   * When true, this field is computed by the backend (e.g. JOIN alias) and is
   * never included in create/edit forms. Shown only in list and detail views.
   */
  displayOnly?: boolean;
  /** Filter entity-select options to rows where this field equals relatedFilterValue */
  relatedFilterField?: string;
  /** The value to match against relatedFilterField */
  relatedFilterValue?: string;
  /** When true, this field is hidden in encounter mode (value is set automatically) */
  hideInEncounterMode?: boolean;
  /**
   * When true, this field is not shown in the create/edit form.
   * The form control is still created (so linkedFields can populate it),
   * but the input is not rendered.
   */
  hideInForm?: boolean;
  /** When true, this field is required when registering a new encounter */
  requiredInEncounter?: boolean;
}

export interface EntityMeta {
  key: string;
  singular: string;
  plural: string;
  icon: string;
  description?: string;
  moduleType?: ModuleType;
  /**
   * Key of the clinical-record entity that this entity can link to for adding encounters.
   * When set, the generic-detail shows an "Agregar Antecedente" button.
   * e.g. appointments → 'clinical-records'
   */
  encounterEntity?: string;
  /**
   * Field in THIS entity that holds the patient name used to find the target record.
   * e.g. in appointments: 'patientName'
   */
  encounterMatchField?: string;
  /** When true, the edit action is hidden in list and detail views */
  disableEdit?: boolean;
  /** When true, the delete action is hidden in list and detail views */
  disableDelete?: boolean;
  /** When true, the "new record" action is hidden and the /new route redirects back to the list */
  disableCreate?: boolean;
  /** Shown instead of the "Crear" button in the empty state when disableCreate is true */
  disableCreateHint?: string;
  /**
   * Grammatical gender of `singular`, used to agree determiners in the UI
   * ("Nueva Sesión", not "Nuevo Sesión"). Only needed when the heuristic in
   * `entityGender()` gets it wrong — leave unset otherwise.
   */
  gender?: 'm' | 'f';
}

export interface EntitySchema {
  entity: EntityMeta;
  fields: FieldDefinition[];
}

/** Full payload returned by the "backend" for a given entity */
export interface EntityPayload {
  schema: EntitySchema;
  data: Record<string, any>[];
}

// ───────────────────────── Grammatical agreement ─────────────────────────────
// Buttons used to hardcode "Nuevo {{ singular }}", which reads wrong for the
// many feminine entities in this app ("Nuevo Sesión", "Nuevo Ficha Psicológica",
// "Nuevo Cita"). Spanish marks gender on the head noun, which is the first word
// of these labels, so the suffix of that word decides.

/** Gender of an entity's `singular` label, honouring an explicit override. */
export function entityGender(entity: EntityMeta): 'm' | 'f' {
  if (entity.gender) return entity.gender;
  const head = (entity.singular ?? '').trim().split(/\s+/)[0].toLowerCase();
  // -a, -ión/-ción/-sión, -dad/-tad, -umbre are reliably feminine in Spanish.
  if (/(a|ión|dad|tad|umbre)$/.test(head)) return 'f';
  return 'm';
}

/** e.g. "Nueva Sesión" / "Nuevo Presupuesto" */
export function newEntityLabel(entity: EntityMeta): string {
  return `${entityGender(entity) === 'f' ? 'Nueva' : 'Nuevo'} ${entity.singular}`;
}

// ─────────────────────── Section titles per specialty ───────────────────────
// The clinical `section` keys ('vitals', 'history', …) are structural: every
// specialty schema reuses the same handful so the shared views can group fields.
// The *heading* shown above each group is NOT structural — it has to read in the
// language of the specialty ("Signos Vitales" for medicina general is nonsense
// above a psychology mental-status exam).
//
// This table is the single source of truth for those headings. It used to live
// only inside clinical-detail, so the read-only ficha said "Estado Mental" while
// the "Nueva Atención" form right next to it still said "SIGNOS VITALES" over
// the very same fields. Both views now read from here.

export type SpecialtyKey =
  | 'medical' | 'psych' | 'dental' | 'kine' | 'nutrition'
  | 'fono' | 'ot' | 'midwife' | 'medtech';

/** Maps a clinical-record entity key to its specialty. Unknown keys are medical. */
export function specialtyFromEntityKey(entityKey: string): SpecialtyKey {
  switch (entityKey) {
    case 'dental-records':    return 'dental';
    case 'psych-records':     return 'psych';
    case 'kine-records':      return 'kine';
    case 'nutrition-records': return 'nutrition';
    case 'fono-records':      return 'fono';
    case 'ot-records':        return 'ot';
    case 'matrona-records':   return 'midwife';
    case 'tecnomed-records':  return 'medtech';
    default:                  return 'medical';
  }
}

type TitleTable = Partial<Record<SpecialtyKey, string>> & { medical: string };

const SECTION_TITLES: Record<string, TitleTable> = {
  vitals: {
    medical: 'Signos Vitales',
    dental: 'Examen Clínico',
    psych: 'Estado Mental',
    kine: 'Evaluación Funcional',
    nutrition: 'Evaluación Nutricional',
    fono: 'Evaluación Fonoaudiológica',
    ot: 'Evaluación Ocupacional',
    midwife: 'Control Clínico',
    medtech: 'Parámetros del Examen',
  },
  history: {
    medical: 'Antecedentes Médicos',
    dental: 'Anamnesis Dental',
    psych: 'Antecedentes Psicológicos',
    kine: 'Antecedentes Kinésicos',
    nutrition: 'Anamnesis Alimentaria',
    fono: 'Antecedentes Fonoaudiológicos',
    ot: 'Antecedentes Ocupacionales',
    midwife: 'Antecedentes Gíneco-Obstétricos',
    medtech: 'Antecedentes del Paciente',
  },
  surgical: {
    medical: 'Intervenciones Quirúrgicas',
    dental: 'Tratamientos Dentales',
    psych: 'Terapias e Intervenciones',
    kine: 'Intervenciones y Plan Kinésico',
    nutrition: 'Cirugías y Metas Nutricionales',
    fono: 'Intervenciones Fonoaudiológicas',
    ot: 'Intervenciones Terapéuticas',
    midwife: 'Procedimientos Realizados',
    medtech: 'Exámenes y Procedimientos',
  },
  medications: {
    medical: 'Medicación Actual',
    psych: 'Plan Terapéutico',
    kine: 'Indicaciones y Tratamiento',
    nutrition: 'Plan Alimentario',
    fono: 'Indicaciones Fonoaudiológicas',
    ot: 'Plan de Terapia Ocupacional',
    midwife: 'Indicaciones y Fármacos',
    medtech: 'Indicaciones del Examen',
  },
  soap: {
    medical: 'Nota Clínica (SOAP)',
    dental: 'Nota de Atención Dental',
    psych: 'Nota de Sesión',
    kine: 'Nota Kinésica',
    nutrition: 'Nota Nutricional',
    fono: 'Nota Fonoaudiológica',
    ot: 'Nota de Terapia Ocupacional',
    midwife: 'Nota de Control',
    medtech: 'Registro del Examen',
  },
  diagnosis: {
    medical: 'Diagnóstico',
  },
  alerts: {
    medical: 'Alertas Clínicas',
    psych: 'Factores de Riesgo',
  },
};

/**
 * Heading for a clinical `section` in a given specialty. Falls back to the
 * medical wording, then to the raw section key, so a schema that invents a new
 * section still renders something rather than blank.
 */
export function sectionTitle(section: string, specialty: SpecialtyKey): string {
  const table = SECTION_TITLES[section];
  if (!table) return section;
  return table[specialty] ?? table.medical;
}
