export type FieldType =
  | 'text'
  | 'email'
  | 'number'
  | 'select'
  | 'textarea'
  | 'date'
  | 'datetime'
  | 'boolean'
  | 'url'
  | 'tel'
  | 'range'
  | 'tags'
  | 'object-list'
  | 'dental-chart'
  | 'periodontal-chart'
  | 'entity-select';

/** Determines which view component renders this entity's overview */
export type ModuleType = 'crud' | 'list' | 'calendar' | 'clinical-record' | 'presupuestos';

export type FieldFormat = 'currency' | 'date' | 'stars' | 'percent' | 'none';
export type FilterType = 'search' | 'select';

export interface SelectOption {
  value: string;
  label: string;
}

export interface FieldDefinition {
  name: string;
  type: FieldType;
  label: string;
  required?: boolean;
  showInList?: boolean;
  showInDetail?: boolean;
  isTitle?: boolean;
  isSubtitle?: boolean;
  isBadge?: boolean;
  options?: SelectOption[];
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  pattern?: string;
  patternMessage?: string;
  minLength?: number;
  maxLength?: number;
  sortable?: boolean;
  filterable?: boolean;
  filterType?: FilterType;
  format?: FieldFormat;
  badgeColors?: Record<string, string>;
  isCalendarStart?: boolean;
  isCalendarEnd?: boolean;
  section?: string;
  isVitalSign?: boolean;
  isAlert?: boolean;
  /**
   * When true, this field does not change between patient encounters.
   * In encounter mode the generic-form renders it read-only.
   */
  isStable?: boolean;
  /**
   * When true, the clinical-detail shows a "Imprimir Receta" button
   * next to this field's section, generating a printable prescription.
   */
  isPrescription?: boolean;
  /** When true, the field belongs to the surgical interventions section */
  isSurgical?: boolean;
  /**
   * When true, the field value is auto-generated by the backend on creation.
   * The field is never shown in create/edit forms; on edit, the existing value
   * is preserved automatically.
   */
  isAutoGenerated?: boolean;
  /**
   * When true, the field becomes read-only once the record has at least one
   * encounter registered. Prevents retroactive changes to critical clinical data.
   */
  lockWhenHasEncounters?: boolean;
  /**
   * When true, this field is encrypted at rest using AES-256-GCM (Zero-Knowledge model).
   * The server only stores ciphertext; only the user's derived key can decrypt it.
   */
  encrypted?: boolean;
  /**
   * For type='select': load options dynamically from this entity key via the
   * CRUD service instead of using the hardcoded `options` array.
   * Use lookupValueField / lookupLabelField to specify which row fields to use.
   * Defaults to 'id' for value and 'label' for label.
   */
  lookupEntity?: string;
  /** Field name in the lookup entity whose value is stored in the record (default: 'id') */
  lookupValueField?: string;
  /** Field name in the lookup entity displayed to the user (default: 'label') */
  lookupLabelField?: string;
  /** For type='entity-select': which entity key to load options from */
  relatedEntity?: string;
  /** Field name in the related entity to use as display label */
  relatedLabelField?: string;
  /** Auto-fill other form fields when this entity-select changes */
  linkedFields?: Array<{ from: string; to: string }>;
  /**
   * When true, this field is computed by the backend (e.g. JOIN alias) and is
   * never included in create/edit forms. Shown only in list and detail views.
   */
  displayOnly?: boolean;
  /** Filter entity-select options to rows where this field equals relatedFilterValue */
  relatedFilterField?: string;
  /** The value to match against relatedFilterField */
  relatedFilterValue?: string;
  /** When true, this field is hidden in encounter mode (value is set automatically) */
  hideInEncounterMode?: boolean;
  /** When true, this field is required when registering a new encounter */
  requiredInEncounter?: boolean;
}

export interface EntityMeta {
  key: string;
  singular: string;
  plural: string;
  icon: string;
  description?: string;
  moduleType?: ModuleType;
  /**
   * Key of the clinical-record entity that this entity can link to for adding encounters.
   * When set, the generic-detail shows an "Agregar Antecedente" button.
   * e.g. appointments → 'clinical-records'
   */
  encounterEntity?: string;
  /**
   * Field in THIS entity that holds the patient name used to find the target record.
   * e.g. in appointments: 'patientName'
   */
  encounterMatchField?: string;
  /** When true, the edit action is hidden in list and detail views */
  disableEdit?: boolean;
  /** When true, the delete action is hidden in list and detail views */
  disableDelete?: boolean;
}

export interface EntitySchema {
  entity: EntityMeta;
  fields: FieldDefinition[];
}

/** Full payload returned by the "backend" for a given entity */
export interface EntityPayload {
  schema: EntitySchema;
  data: Record<string, any>[];
}
