import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';
import { SchemaService } from '../../services/schema.service';
import { GenericCrudService } from '../../services/generic-crud.service';
import { EntitySchema, FieldDefinition, SelectOption } from '../../models/entity-schema.model';
import { GoogleCalendarService } from '../../services/google-calendar.service';
import { AuthService } from '../../services/auth.service';

@Component({
    selector: 'app-generic-form',
    imports: [CommonModule, ReactiveFormsModule, RouterLink],
    templateUrl: './generic-form.component.html',
    styleUrl: './generic-form.component.scss'
})
export class GenericFormComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private fb = inject(FormBuilder);
  private schemaService = inject(SchemaService);
  private crudService = inject(GenericCrudService);
  readonly gcalSvc = inject(GoogleCalendarService);
  private auth = inject(AuthService);

  schema = signal<EntitySchema | null>(null);
  entityKey = signal('');
  isEdit = signal(false);
  recordId = signal<number | null>(null);
  saving = signal(false);
  saved = signal(false);
  saveError = signal<string | null>(null);
  isEncounterMode = signal(false);
  /** True when the record being edited already has at least one encounter */
  hasEncounters = signal(false);
  gcalStatus = signal<'idle' | 'syncing' | 'synced' | 'not_connected' | 'error'>('idle');
  form!: FormGroup;

  editableFields = computed(() => {
    const fields = this.schema()?.fields ?? [];
    const excluded = (f: FieldDefinition) =>
      f.type === 'object-list' || f.type === 'dental-chart' || f.type === 'periodontal-chart' ||
      f.isAutoGenerated || f.type === 'entity-select' || !!f.displayOnly || !!f.hideInForm;
    return fields.filter(f => !excluded(f));
  });

  /** entity-select fields — shown only in create mode */
  entitySelectFields = computed(() => {
    if (this.isEdit() || this.isEncounterMode()) return [];
    return this.schema()?.fields.filter(f => f.type === 'entity-select') ?? [];
  });

  ngOnInit() {
    const key = this.route.snapshot.paramMap.get('entityKey') ?? '';
    const idParam = this.route.snapshot.paramMap.get('id');
    const encounterMode = !!this.route.snapshot.data['encounterMode'];

    this.entityKey.set(key);
    this.schema.set(this.schemaService.getSchema(key));
    this.crudService.initStore(key);
    this.isEncounterMode.set(encounterMode);

    if (idParam) {
      this.isEdit.set(true);
      this.recordId.set(+idParam);
    }

    this.buildForm();

    // Auto-fill professional name in create mode
    if (!idParam && !encounterMode) {
      const userName = this.auth.user()?.name;
      if (userName) {
        const PROF_FIELDS = ['doctor', 'doctorName', 'professionalName', 'professional', 'therapist', 'psychologist', 'dentist'];
        PROF_FIELDS.forEach(n => { if (this.form.get(n)) this.form.get(n)!.setValue(userName); });
      }
    }

    // Pre-load options for entity-select and lookup-select fields
    this.schema()?.fields
      .filter(f => f.type === 'entity-select' && f.relatedEntity)
      .forEach(f => this.crudService.initStore(f.relatedEntity!));
    this.schema()?.fields
      .filter(f => f.type === 'select' && f.lookupEntity)
      .forEach(f => this.crudService.initStore(f.lookupEntity!));

    if (this.recordId() !== null) {
      const record = this.crudService.getById(key, this.recordId()!);
      if (record) {
        const patchValue: Record<string, any> = {};
        this.schema()!.fields.forEach(f => {
          if (f.type === 'tags' && Array.isArray(record[f.name])) {
            patchValue[f.name] = record[f.name].join(', ');
          } else {
            patchValue[f.name] = record[f.name] ?? '';
          }
        });
        this.form.patchValue(patchValue);

        // Lock fields that must not change once encounters exist
        const encounters = record['encounters'];
        if (Array.isArray(encounters) && encounters.length > 0) {
          this.hasEncounters.set(true);
          this.schema()?.fields
            .filter(f => f.lockWhenHasEncounters)
            .forEach(f => this.form.get(f.name)?.disable());
        }
      }
    }
  }

  private buildForm() {
    const group: Record<string, any> = {};
    const schema = this.schema();
    const fields = schema?.fields.filter(f =>
      f.type !== 'object-list' && f.type !== 'dental-chart' && f.type !== 'periodontal-chart' &&
      !f.isAutoGenerated && !f.displayOnly
    ) ?? [];

    fields.forEach(f => {
      const validators = [];
      // hideInForm fields are auto-filled by linkedFields — skip user-facing validators
      if (!f.hideInForm) {
        if (f.required) validators.push(Validators.required);
        if (f.type === 'email') validators.push(Validators.email);
        if (f.pattern) validators.push(Validators.pattern(f.pattern));
        if (f.minLength) validators.push(Validators.minLength(f.minLength));
        if (f.maxLength) validators.push(Validators.maxLength(f.maxLength));
        if (f.min !== undefined && f.type === 'number') validators.push(Validators.min(f.min));
        if (f.max !== undefined && f.type === 'number') validators.push(Validators.max(f.max));
      }

      let defaultVal: any = '';
      if (f.type === 'number') defaultVal = f.min ?? 0;
      if (f.type === 'range')  defaultVal = f.min ?? 0;
      if (f.type === 'boolean') defaultVal = false;
      if (f.options && f.options.length > 0) defaultVal = f.options[0].value;

      group[f.name] = [defaultVal, validators];
    });

    this.form = this.fb.group(group);
  }

  getEntityOptions(field: FieldDefinition): Array<{ id: any; label: string; raw: Record<string, any> }> {
    if (!field.relatedEntity) return [];
    let options = this.crudService.getAll(field.relatedEntity)().map(item => ({
      id:    item['id'],
      label: String(item[field.relatedLabelField ?? 'nombre'] ?? item['name'] ?? item['id']),
      raw:   item
    }));
    if (field.relatedFilterField && field.relatedFilterValue) {
      options = options.filter(o =>
        String(o.raw[field.relatedFilterField!]) === field.relatedFilterValue
      );
    }
    return options;
  }

  getFieldOptions(field: FieldDefinition): SelectOption[] {
    if (!field.lookupEntity) return field.options ?? [];
    const vf = field.lookupValueField ?? 'id';
    const lf = field.lookupLabelField ?? 'label';
    return this.crudService.getAll(field.lookupEntity)().map(item => ({
      value: String(item[vf] ?? item['id']),
      label: String(item[lf] ?? item['label'] ?? item[vf] ?? item['id'])
    }));
  }

  onEntitySelect(field: FieldDefinition, selectedId: string): void {
    // Value is already set by [formControlName] — only handle linked field patching
    if (!field.linkedFields || !selectedId) return;
    const selected = this.getEntityOptions(field).find(o => String(o.id) === String(selectedId));
    if (!selected) return;
    const patch: Record<string, any> = {};
    field.linkedFields.forEach(link => { patch[link.to] = selected.raw[link.from] ?? ''; });
    this.form.patchValue(patch);
    field.linkedFields.forEach(link => { this.form.get(link.to)?.disable(); });
  }

  selectedPatientInfo(field: FieldDefinition): string | null {
    const selectedId = this.ctrl(field.name)?.value;
    if (!selectedId) return null;
    const opt = this.getEntityOptions(field).find(o => String(o.id) === String(selectedId));
    return opt ? opt.label : null;
  }

  trackEntityOption(_: number, opt: { id: any; label: string; raw: Record<string, any> }): any {
    return opt.id;
  }

  ctrl(name: string): AbstractControl {
    return this.form.get(name)!;
  }

  isInvalid(name: string): boolean {
    const ctrl = this.form.get(name);
    return !!(ctrl?.invalid && ctrl.touched);
  }

  getError(name: string, field: FieldDefinition): string {
    const ctrl = this.form.get(name);
    if (!ctrl?.errors) return '';
    if (ctrl.errors['required'])  return `${field.label} es obligatorio.`;
    if (ctrl.errors['email'])     return 'El email no es válido.';
    if (ctrl.errors['pattern'])   return field.patternMessage ?? 'El formato no es válido.';
    if (ctrl.errors['minlength']) return `Mínimo ${field.minLength} caracteres.`;
    if (ctrl.errors['maxlength']) return `Máximo ${field.maxLength} caracteres.`;
    if (ctrl.errors['min'])       return `El valor mínimo es ${field.min}.`;
    if (ctrl.errors['max'])       return `El valor máximo es ${field.max}.`;
    return '';
  }

  submit() {
    this.form.markAllAsTouched();
    if (this.form.invalid) return;

    this.saving.set(true);
    this.saveError.set(null);
    const raw = this.form.getRawValue();

    const processFields = (): Record<string, any> => {
      const out: Record<string, any> = {};
      this.schema()!.fields.filter(f => f.type !== 'object-list').forEach(f => {
        if (f.isAutoGenerated) {
          if (this.isEdit() && this.recordId() !== null) {
            const existing = this.crudService.getById(this.entityKey(), this.recordId()!);
            if (existing?.[f.name]) out[f.name] = existing[f.name];
          } else {
            out[f.name] = this.generateId(f);
          }
          return;
        }
        const v = raw[f.name];
        if (v === undefined) return;
        if (f.type === 'entity-select' && !v) return;
        if (f.type === 'tags') {
          out[f.name] = v ? String(v).split(',').map((t: string) => t.trim()).filter(Boolean) : [];
        } else if (f.type === 'number' || f.type === 'range') {
          out[f.name] = Number(v);
        } else {
          out[f.name] = v;
        }
      });
      return out;
    };

    setTimeout(() => {
      const processed = processFields();
      if (this.isEncounterMode() && this.recordId() !== null) {
        // Build a new encounter object from only the mutable fields + encounter date
        const profName = this.auth.user()?.name;
        const encounter: Record<string, any> = {
          encounterDate: raw['encounterDate'],
          ...(profName ? { encounterDoctor: profName } : {})
        };
        (this.schema()!.fields.filter(f => !f.isStable && f.type !== 'object-list' && f.type !== 'dental-chart' && f.type !== 'periodontal-chart')).forEach(f => {
          const v = raw[f.name];
          if (v !== undefined && v !== '' && v !== null) {
            encounter[f.name] = (f.type === 'number' || f.type === 'range') ? Number(v) : v;
          }
        });
        this.crudService.appendEncounter(this.entityKey(), this.recordId()!, encounter).subscribe({
          next: () => {
            this.saving.set(false);
            this.saved.set(true);
            setTimeout(() => this.router.navigate(['/app/clinical', this.entityKey(), this.recordId()]), 800);
          },
          error: (err) => { this.saving.set(false); this.saveError.set(err?.error?.message ?? 'Error al guardar la atención.'); }
        });
      } else if (this.isEdit() && this.recordId() !== null) {
        this.crudService.update(this.entityKey(), this.recordId()!, processed).subscribe({
          next: () => {
            this.saving.set(false);
            this.saved.set(true);
            setTimeout(() => this.router.navigate(this.listRoute()), 800);
          },
          error: (err) => { this.saving.set(false); this.saveError.set(err?.error?.message ?? 'Error al guardar los cambios.'); }
        });
      } else {
        this.crudService.create(this.entityKey(), processed).subscribe({
          next: (created) => {
            this.linkPatientToProfessional(created);
            this.syncToGoogleCalendar(processed);
            this.saving.set(false);
            this.saved.set(true);
            setTimeout(() => this.router.navigate(this.listRoute()), 800);
          },
          error: (err) => { this.saving.set(false); this.saveError.set(err?.error?.message ?? 'Error al crear el registro.'); }
        });
      }
    }, 400);
  }

  listRoute(): string[] {
    return this.schema()?.entity.moduleType === 'clinical-record'
      ? ['/app/clinical', this.entityKey()]
      : ['/app/entity', this.entityKey()];
  }

  cancel() {
    this.router.navigate(this.listRoute());
  }

  getInputType(field: FieldDefinition): string {
    if (field.type === 'tags') return 'text';
    if (field.type === 'datetime') return 'datetime-local';
    return field.type as string;
  }

  private generateId(field: FieldDefinition): string {
    const match = field.pattern?.match(/^\^([A-Z]+)-/);
    const prefix = match?.[1] ?? 'ID';
    const num = String(Date.now() % 100000).padStart(5, '0');
    return `${prefix}-${num}`;
  }

  /**
   * When a professional creates a new patient, silently create a placeholder
   * appointment linking the patient to the professional. The patients table has
   * no professional_id column, so "patients of a professional" is derived from
   * appointments — this makes the new patient visible in professional-scoped lists.
   */
  private linkPatientToProfessional(created: Record<string, any> | null | undefined): void {
    if (this.entityKey() !== 'patients') return;
    if (!this.auth.isProfessionalView()) return;
    const profId = this.auth.myProfessionalId();
    const patientId = created?.['id'];
    if (profId == null || patientId == null) return;

    this.crudService.create('appointments', {
      patientId,
      professionalId: profId,
      patientName: created!['name'] ?? created!['nombre'] ?? '',
      professionalName: this.auth.user()?.professionalName ?? this.auth.user()?.name ?? '',
      status: 'scheduled',
      reason: 'Alta de paciente',
      dateTime: new Date().toISOString()
    }).subscribe({
      next: () => {},
      error: () => {} // silent — linking is best-effort, never surfaces to the user
    });
  }

  private syncToGoogleCalendar(data: Record<string, any>): void {
    const schema = this.schema();
    if (!schema || schema.entity.moduleType !== 'calendar') return;

    const startF = schema.fields.find(f => f.isCalendarStart);
    if (!startF) return;

    if (!this.gcalSvc.isConnected()) {
      this.gcalStatus.set('not_connected');
      return;
    }

    const endF   = schema.fields.find(f => f.isCalendarEnd);
    const titleF = schema.fields.find(f => f.isTitle);
    const subF   = schema.fields.find(f => f.isSubtitle);
    const emailF = schema.fields.find(f => f.type === 'email');

    this.gcalStatus.set('syncing');
    this.gcalSvc.createEvent({
      summary:       String(data[titleF?.name ?? ''] || schema.entity.singular),
      description:   subF ? String(data[subF.name] || '') : '',
      startIso:      String(data[startF.name] || ''),
      endIso:        endF ? String(data[endF.name] || '') : undefined,
      attendeeEmail: emailF ? String(data[emailF.name] || '') : undefined
    }).then(result => {
      this.gcalStatus.set(result.success ? 'synced' : 'error');
    });
  }
}
